apps/news/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings


app_name="news"
urlpatterns = [
    url(r'^$', views.show, name='show'),
    url(r'^new$', views.new, name='new'),
    url(r'^create$', views.create, name='create'),
    url(r'^show$', views.show, name='show'),
    url(r'^detail/(?P<news_id>\d+)$', views.newsDetail, name='news_detail'),



]

apps/personnel/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings

from django.conf.urls.static import static

from django.views.static import serve



app_name="personnel"
urlpatterns = [
    url(r'^$', views.show, name='show'),
    url(r'^new$', views.new, name='new'),
    url(r'^create$', views.create, name='create'),
    url(r'^show$', views.show, name='show'),
    url(r'^show/(?P<user_id>\d+)$', views.view, name='view'),



]

# make sure to change media serve for production use a front end server for media files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

apps/wins/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings


app_name="wins"
urlpatterns = [
    url(r'^$', views.show, name='show'),
    url(r'^new$', views.new, name='new'),
    url(r'^create$', views.create, name='create'),
    url(r'^show$', views.show, name='show'),
    url(r'^detail/(?P<win_id>\d+)$', views.winDetail, name='win_detail'),


]

hub/urls.py
from django.contrib import admin
from django.conf.urls import url,include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.main.urls',namespace='main' , app_name='main')),
    url(r'^personnel/', include('apps.personnel.urls',namespace='personnel' , app_name='personnel')),
    url(r'^news/', include('apps.news.urls',namespace='news' , app_name='news')),
    url(r'^wins/', include('apps.wins.urls',namespace='wins' , app_name='wins')),



]

apps/news/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django import forms

# Create your models here.


class News (models.Model):
    title = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)


class NewsForm (forms.ModelForm):
    description = forms.CharField( widget=forms.Textarea(attrs={'class': 'form-control'}))
    class Meta:
        model = News
        fields = ('title','description')

apps/personnel/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django import forms

# Create your models here.

def user_directory_path(instance,filename):
    return 'user_{0}/{1}'.format(instance.user.id,filename)

class Personnel (models.Model):
    first_name = models.CharField(max_length=255, blank=True)
    last_name = models.CharField(max_length=255, blank=True)
    fun_fact = models.CharField(max_length=255, blank=True)
    profile_image = models.FileField (upload_to = 'profile_images/')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)


class PersonnelForm (forms.ModelForm):
    class Meta:
        model = Personnel
        fields = ('first_name','last_name', 'fun_fact', 'profile_image')

apps/wins/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django import forms

# Create your models here.


class Wins (models.Model):
    title = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)


class WinsForm (forms.ModelForm):
    description = forms.CharField( widget=forms.Textarea(attrs={'class': 'form-control'}))
    class Meta:
        model = Wins
        fields = ('title','description')

apps/main/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect,reverse
from django.contrib import messages
from ..personnel.models import Personnel
from ..news.models import News
from ..wins.models import Wins
from ..personnel.personnel_serializer import PersonnelSerializer
from ..personnel.json_encoder import JSONEncoder


import json

status=""

def index(request):
    print("index")
    all_personnel = Personnel.objects.all()
    serializedPersonnel = PersonnelSerializer(all_personnel, many = True)

    context ={
    "news": News.objects.order_by('created_at')[:3],
    "wins": Wins.objects.order_by('created_at')[:3],
    "personnel":json.dumps(serializedPersonnel.data)
    }
    return render(request,"main/index.html",context)

apps/news/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect,reverse

from django.contrib import messages

from .models import News, NewsForm

# Create your views here.


def new(request):
    form = NewsForm()
    return render(request,'news/new.html',{'form':form})

def create(request):
    print("create personnel")
    if request.method == 'POST':
        print ("hello")
        form = NewsForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse('news:show'))
        else:
            form = NewsForm()
    return render(request,'news/new.html',{'form':form})

def show(request):
    context = {
    "news": News.objects.all()
    }
    return render(request, 'news/show.html', context)

def newsDetail (request,news_id):

    context = {
        "news": News.objects.filter(id=news_id)[0]
    }
    return render(request,'news/display.html',context)

apps/personnel/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect,reverse

from django.contrib import messages

from .models import PersonnelForm,Personnel

# Create your views here.
def new(request):
    form = PersonnelForm()
    return render(request,'personnel/new.html',{'form':form})

def create(request):
    print("create personnel")
    if request.method == 'POST':
        print ("hello")
        form = PersonnelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse('personnel:show'))
        else:
            form = PersonnelForm()
    return render(request,'personnel/new.html',{'form':form})

def show(request):
    context = {
        "personnel": Personnel.objects.all()
    }
    return render(request,'personnel/show.html',context)

def view (request,user_id):
    context = {
        "person": Personnel.objects.filter(user_id)[0]
    }
    return render(request,'personnel/display.html')

apps/wins/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect,reverse

from django.contrib import messages

from .models import Wins, WinsForm

# Create your views here.


def new(request):
    form = WinsForm()
    return render(request,'wins/new.html',{'form':form})

def create(request):
    print("create personnel")
    if request.method == 'POST':
        print ("hello")
        form = WinsForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse('wins:show'))
        else:
            form = WinsForm()
    return render(request,'wins/new.html',{'form':form})

def show(request):
    context = {
    "wins": Wins.objects.all()
    }
    return render(request, 'wins/show.html', context)

def winDetail (request,win_id):

    context = {
        "win": Wins.objects.filter(id=win_id)[0]
    }
    return render(request,'wins/display.html',context)

apps/main/templates/main/index.html
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <title>Hub</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap-4.0.0-dist/css/bootstrap.min.css' %}" >
    <!-- google -->
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/style.css' %}" >
    <script src="{% static 'jquery/dist/jquery.min.js' %}" ></script>
    <script src="{% static 'bootstrap-4.0.0-dist/js/bootstrap.min.js' %}" ></script>



  </head>
  <body>
 <div class="container">
   </div>
     <img class="col-10" id="landing_page_logo" src="{% static 'images/icons/landing_page_logo.png'%}" alt="">
     <div class="col-12 nav_bar">
       <div class="hub-circle kitchen col-2">
         <a href="#">
         <img class="icon-img" alt="kitchen" src="{% static 'images/icons/kitchen_icon.png'%}" alt="">
         </a>
       </div>
       <div class="hub-circle library col-2">
         <a href="#">
         <img class="icon-img" alt="kitchen" src="{% static 'images/icons/library_icon.png'%}" alt="">
         </a>
       </div>
       <div class="hub-circle living-room col-2">
         <a href="#">
         <img class="icon-img" alt="kitchen" src="{% static 'images/icons/living_room_icon.png'%}" alt="">
         </a>
       </div>
       <div class="hub-circle neighborhood col-2">
         <a href="#">
         <img class="icon-img" alt="kitchen" src="{% static 'images/icons/neighborhood_icon.png'%}" alt="">
         </a>
       </div>
       <div class="hub-circle study col-2">
         <a href="#">
         <img  class="icon-img" alt="kitchen" src="{% static 'images/icons/workshop_icon.png'%}" alt="">
         </a>
       </div>
       <div class="hub-circle workshop">
         <a href="#">
         <img class="icon-img" alt="kitchen" src="{% static 'images/icons/study_icon.png'%}" alt="">
         </a>
       </div>

     </div>



<div class="main-container">
  <div class="row">
    <div class="cont-1 col-sm">
      <a class="col-12 slogan-header" href="{% url 'wins:show' %}">ACS Wins</a>
      <div class="sub-div col-12">
        <ol>
          {% for win in wins%}
          <li><a href="/wins/detail/{{win.id}}">{{win.title}}</a>
        <p class="snippets">{{win.description}}</p></li>
          {% endfor %}
        </ol>

      </div>
    </div>
    <div class="cont-2 col-sm">
      <a class="col-12 slogan-header" href="{% url 'news:show' %}">ACS News</a>
      <div class="sub-div col-12">
        <ol>
          {% for n in news %}
          <li><a href="/news/detail/{{n.id}}">{{n.title}}</a>
        <p class="snippets">{{n.description}}</p></li>

          {% endfor %}

        </ol>

      </div>
    </div>
    <div class="cont-3 col-sm">
      <a class="col-12 slogan-header" href="{% url 'personnel:show' %}">ACS Family</a>
      <div class="profile-div col-10">
        <div class="profile-img col-10">
          <img id="person_image" class="col-12" src="{% static 'images/profiles/man_2.jpg'%}" alt="profile_img">

        </div>
        <p align="center" id="fun-fact">Lorem ipsum dolor amet godard post-ironic jianbing chillwave, franzen offal 3 wolf moon meggings jean shorts edison bulb kale chips DIY snackwave</p>

      </div>
    </div>
  </div>
</div>

   </div>



   <script type="text/javascript">
   var personnel = '{{personnel |safe}}';
   </script>
    <script src="{% static 'js/handler.js' %}" ></script>
    <script src="{% static 'js/carousel.js' %}" ></script>

  </body>
</html>

apps/news/templates/news/base.html
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <title>Hub</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap-4.0.0-dist/css/bootstrap.min.css' %}" >
    <!-- google -->
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/style.css' %}" >
    <script src="{% static 'jquery/dist/jquery.min.js' %}" ></script>
    <script src="{% static 'bootstrap-4.0.0-dist/js/bootstrap.min.js' %}" ></script>
    <script src="{% static 'js/handler.js' %}" ></script>

  </head>

<body>
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>


</body>


</html>

apps/news/templates/news/display.html
{% extends 'news/base.html'%}
{% block body %}


<h1>{{news.title}}</h1>
<p>{{news.description}}</p>
<p>{{news.created_at}}</p>

{% endblock %}

apps/news/templates/news/new.html
{% extends 'news/base.html'%}
{% block body %}

    <h1>Publish News</h1>
    <form class="personnel-form" action="{% url 'news:create'%}" enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn btn-danger" type="submit" name="button">Submit</button>

    </form>

  </body>
</html>

{% endblock %}

apps/news/templates/news/show.html
{% extends 'news/base.html'%}
{% block body %}
    <h1>ACS News</h1>
    <table class="table">
      <thead>

          <th scope="column">Title</th>
          <th scope="column">Article</th>
          <th scope="column">Published Date</th>

        </tr>
      </thead>
      <tbody>
        {% for n in news %}
        <tr>
          <td><a href="/news/detail/{{n.id}}">{{n.title}}</a></td>
          <td>{{n.description}}</td>
          <td>{{n.created_at}}</td>
        </tr>

        {% endfor %}

      </tbody>

    </table>

{% endblock %}

apps/personnel/templates/personnel/base.html
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <title>Hub</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap-4.0.0-dist/css/bootstrap.min.css' %}" >
    <!-- google -->
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/style.css' %}" >
    <script src="{% static 'jquery/dist/jquery.min.js' %}" ></script>
    <script src="{% static 'bootstrap-4.0.0-dist/js/bootstrap.min.js' %}" ></script>
    <script src="{% static 'js/handler.js' %}" ></script>

  </head>

<body>
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>


</body>


</html>

apps/personnel/templates/personnel/display.html
{% extends 'personnel/base.html'%}
{% block body %}

{{person}}

{% endblock %}

apps/personnel/templates/personnel/new.html
{% extends 'personnel/base.html'%}
{% block body %}

<h1>Add Personnel</h1>
    <form class="personnel-form" action="{% url 'personnel:create'%}" enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn btn-danger" type="submit" name="button">Submit</button>

    </form>

{% endblock %}

apps/personnel/templates/personnel/show.html
{% extends 'personnel/base.html'%}
{% block body %}
    <h1>Personnel</h1>
    <table class="table">
      <thead>
        <tr>
          <th scope="column"></th>
          <th scope="column">First Name</th>
          <th scope="column">Last Name</th>
          <th scope="column">Fun Fact</th>
        </tr>
      </thead>
      <tbody>
        {% for person in personnel %}
        <tr>
          <td><img src="/personnel{{person.profile_image.url}}" alt="profile image" style="width:100px;height:100px;"></td>
          <td>{{person.first_name}}</td>
          <td>{{person.last_name}}</td>
          <td>{{person.fun_fact}}</td>
        </tr>

        {% endfor %}

      </tbody>

    </table>

{% endblock %}

apps/wins/templates/wins/base.html
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <title>Hub</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap-4.0.0-dist/css/bootstrap.min.css' %}" >
    <!-- google -->
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/style.css' %}" >
    <script src="{% static 'jquery/dist/jquery.min.js' %}" ></script>
    <script src="{% static 'bootstrap-4.0.0-dist/js/bootstrap.min.js' %}" ></script>
    <script src="{% static 'js/handler.js' %}" ></script>

  </head>

<body>
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>


</body>


</html>

apps/wins/templates/wins/display.html
{% extends 'news/base.html'%}
{% block body %}

<h1>{{win.title}}</h1>
<p>{{win.description}}</p>
<p>{{win.created_at}}</p>

{% endblock %}

apps/wins/templates/wins/new.html
{% extends 'wins/base.html'%}
{% block body %}

    <h1>Announce Win</h1>
    <form class="personnel-form" action="{% url 'wins:create'%}" enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn btn-danger" type="submit" name="button">Submit</button>

    </form>

  </body>
</html>

{% endblock %}

apps/wins/templates/wins/show.html
{% extends 'wins/base.html'%}
{% block body %}
    <h1>ACS Wins</h1>
    <table class="table">
      <thead>
          <th scope="column">Title</th>
          <th scope="column">Article</th>
          <th scope="column">Published Date</th>

        </tr>
      </thead>
      <tbody>
        {% for win in wins %}
        <tr>
          <td><a href="/wins/detail/{{win.id}}">{{win.title}}</a></td>
          <td>{{win.description}}</td>
          <td>{{win.created_at}}</td>
        </tr>

        {% endfor %}

      </tbody>

    </table>

{% endblock%}